inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'lib/opentelemetry/**/*.rb'

Layout/LineLength:
  Max: 140

Lint/UnusedMethodArgument:
  Enabled: false

Metrics:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'test/**/*.rb'

Style/FetchEnvVar:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'test/helper.rb'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RequireOrder:
  Enabled: true

